// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/api/api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignUpRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{1}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SuccessReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuccessReply) Reset()         { *m = SuccessReply{} }
func (m *SuccessReply) String() string { return proto.CompactTextString(m) }
func (*SuccessReply) ProtoMessage()    {}
func (*SuccessReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{2}
}

func (m *SuccessReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuccessReply.Unmarshal(m, b)
}
func (m *SuccessReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuccessReply.Marshal(b, m, deterministic)
}
func (m *SuccessReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuccessReply.Merge(m, src)
}
func (m *SuccessReply) XXX_Size() int {
	return xxx_messageInfo_SuccessReply.Size(m)
}
func (m *SuccessReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SuccessReply.DiscardUnknown(m)
}

var xxx_messageInfo_SuccessReply proto.InternalMessageInfo

type SignInRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{3}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SignInReply struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInReply) Reset()         { *m = SignInReply{} }
func (m *SignInReply) String() string { return proto.CompactTextString(m) }
func (*SignInReply) ProtoMessage()    {}
func (*SignInReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{4}
}

func (m *SignInReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInReply.Unmarshal(m, b)
}
func (m *SignInReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInReply.Marshal(b, m, deterministic)
}
func (m *SignInReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInReply.Merge(m, src)
}
func (m *SignInReply) XXX_Size() int {
	return xxx_messageInfo_SignInReply.Size(m)
}
func (m *SignInReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInReply.DiscardUnknown(m)
}

var xxx_messageInfo_SignInReply proto.InternalMessageInfo

func (m *SignInReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshRequest) Reset()         { *m = RefreshRequest{} }
func (m *RefreshRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshRequest) ProtoMessage()    {}
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{5}
}

func (m *RefreshRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshRequest.Unmarshal(m, b)
}
func (m *RefreshRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshRequest.Marshal(b, m, deterministic)
}
func (m *RefreshRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshRequest.Merge(m, src)
}
func (m *RefreshRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshRequest.Size(m)
}
func (m *RefreshRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshRequest proto.InternalMessageInfo

type RefreshReply struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshReply) Reset()         { *m = RefreshReply{} }
func (m *RefreshReply) String() string { return proto.CompactTextString(m) }
func (*RefreshReply) ProtoMessage()    {}
func (*RefreshReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{6}
}

func (m *RefreshReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshReply.Unmarshal(m, b)
}
func (m *RefreshReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshReply.Marshal(b, m, deterministic)
}
func (m *RefreshReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshReply.Merge(m, src)
}
func (m *RefreshReply) XXX_Size() int {
	return xxx_messageInfo_RefreshReply.Size(m)
}
func (m *RefreshReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshReply.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshReply proto.InternalMessageInfo

func (m *RefreshReply) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type NewChanRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewChanRequest) Reset()         { *m = NewChanRequest{} }
func (m *NewChanRequest) String() string { return proto.CompactTextString(m) }
func (*NewChanRequest) ProtoMessage()    {}
func (*NewChanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{7}
}

func (m *NewChanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewChanRequest.Unmarshal(m, b)
}
func (m *NewChanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewChanRequest.Marshal(b, m, deterministic)
}
func (m *NewChanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewChanRequest.Merge(m, src)
}
func (m *NewChanRequest) XXX_Size() int {
	return xxx_messageInfo_NewChanRequest.Size(m)
}
func (m *NewChanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewChanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewChanRequest proto.InternalMessageInfo

func (m *NewChanRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type JoinChanRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinChanRequest) Reset()         { *m = JoinChanRequest{} }
func (m *JoinChanRequest) String() string { return proto.CompactTextString(m) }
func (*JoinChanRequest) ProtoMessage()    {}
func (*JoinChanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{8}
}

func (m *JoinChanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinChanRequest.Unmarshal(m, b)
}
func (m *JoinChanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinChanRequest.Marshal(b, m, deterministic)
}
func (m *JoinChanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinChanRequest.Merge(m, src)
}
func (m *JoinChanRequest) XXX_Size() int {
	return xxx_messageInfo_JoinChanRequest.Size(m)
}
func (m *JoinChanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinChanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinChanRequest proto.InternalMessageInfo

func (m *JoinChanRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Channel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owned                bool     `protobuf:"varint,3,opt,name=owned,proto3" json:"owned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{9}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetOwned() bool {
	if m != nil {
		return m.Owned
	}
	return false
}

type GetChansRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChansRequest) Reset()         { *m = GetChansRequest{} }
func (m *GetChansRequest) String() string { return proto.CompactTextString(m) }
func (*GetChansRequest) ProtoMessage()    {}
func (*GetChansRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{10}
}

func (m *GetChansRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChansRequest.Unmarshal(m, b)
}
func (m *GetChansRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChansRequest.Marshal(b, m, deterministic)
}
func (m *GetChansRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChansRequest.Merge(m, src)
}
func (m *GetChansRequest) XXX_Size() int {
	return xxx_messageInfo_GetChansRequest.Size(m)
}
func (m *GetChansRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChansRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChansRequest proto.InternalMessageInfo

type SearchChansRequest struct {
	Input                string   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchChansRequest) Reset()         { *m = SearchChansRequest{} }
func (m *SearchChansRequest) String() string { return proto.CompactTextString(m) }
func (*SearchChansRequest) ProtoMessage()    {}
func (*SearchChansRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{11}
}

func (m *SearchChansRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchChansRequest.Unmarshal(m, b)
}
func (m *SearchChansRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchChansRequest.Marshal(b, m, deterministic)
}
func (m *SearchChansRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchChansRequest.Merge(m, src)
}
func (m *SearchChansRequest) XXX_Size() int {
	return xxx_messageInfo_SearchChansRequest.Size(m)
}
func (m *SearchChansRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchChansRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchChansRequest proto.InternalMessageInfo

func (m *SearchChansRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type ChansReply struct {
	Channels             []*Channel `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ChansReply) Reset()         { *m = ChansReply{} }
func (m *ChansReply) String() string { return proto.CompactTextString(m) }
func (*ChansReply) ProtoMessage()    {}
func (*ChansReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{12}
}

func (m *ChansReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChansReply.Unmarshal(m, b)
}
func (m *ChansReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChansReply.Marshal(b, m, deterministic)
}
func (m *ChansReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChansReply.Merge(m, src)
}
func (m *ChansReply) XXX_Size() int {
	return xxx_messageInfo_ChansReply.Size(m)
}
func (m *ChansReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ChansReply.DiscardUnknown(m)
}

var xxx_messageInfo_ChansReply proto.InternalMessageInfo

func (m *ChansReply) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type LeaveChanRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveChanRequest) Reset()         { *m = LeaveChanRequest{} }
func (m *LeaveChanRequest) String() string { return proto.CompactTextString(m) }
func (*LeaveChanRequest) ProtoMessage()    {}
func (*LeaveChanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{13}
}

func (m *LeaveChanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveChanRequest.Unmarshal(m, b)
}
func (m *LeaveChanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveChanRequest.Marshal(b, m, deterministic)
}
func (m *LeaveChanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveChanRequest.Merge(m, src)
}
func (m *LeaveChanRequest) XXX_Size() int {
	return xxx_messageInfo_LeaveChanRequest.Size(m)
}
func (m *LeaveChanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveChanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveChanRequest proto.InternalMessageInfo

func (m *LeaveChanRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Connect struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connect) Reset()         { *m = Connect{} }
func (m *Connect) String() string { return proto.CompactTextString(m) }
func (*Connect) ProtoMessage()    {}
func (*Connect) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{14}
}

func (m *Connect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connect.Unmarshal(m, b)
}
func (m *Connect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connect.Marshal(b, m, deterministic)
}
func (m *Connect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connect.Merge(m, src)
}
func (m *Connect) XXX_Size() int {
	return xxx_messageInfo_Connect.Size(m)
}
func (m *Connect) XXX_DiscardUnknown() {
	xxx_messageInfo_Connect.DiscardUnknown(m)
}

var xxx_messageInfo_Connect proto.InternalMessageInfo

type Disconnect struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disconnect) Reset()         { *m = Disconnect{} }
func (m *Disconnect) String() string { return proto.CompactTextString(m) }
func (*Disconnect) ProtoMessage()    {}
func (*Disconnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{15}
}

func (m *Disconnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disconnect.Unmarshal(m, b)
}
func (m *Disconnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disconnect.Marshal(b, m, deterministic)
}
func (m *Disconnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disconnect.Merge(m, src)
}
func (m *Disconnect) XXX_Size() int {
	return xxx_messageInfo_Disconnect.Size(m)
}
func (m *Disconnect) XXX_DiscardUnknown() {
	xxx_messageInfo_Disconnect.DiscardUnknown(m)
}

var xxx_messageInfo_Disconnect proto.InternalMessageInfo

type PublishRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{16}
}

func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (m *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(m, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PublishRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type MessageData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Seq                  int32    `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageData) Reset()         { *m = MessageData{} }
func (m *MessageData) String() string { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()    {}
func (*MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{17}
}

func (m *MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageData.Unmarshal(m, b)
}
func (m *MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageData.Marshal(b, m, deterministic)
}
func (m *MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageData.Merge(m, src)
}
func (m *MessageData) XXX_Size() int {
	return xxx_messageInfo_MessageData.Size(m)
}
func (m *MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageData proto.InternalMessageInfo

func (m *MessageData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MessageData) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *MessageData) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Ping struct {
	Timestamp            uint64   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{18}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Pong struct {
	Timestamp            uint64   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{19}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ClientUpdate struct {
	// Types that are valid to be assigned to Message:
	//	*ClientUpdate_Up
	//	*ClientUpdate_Ping
	//	*ClientUpdate_Down
	Message              isClientUpdate_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ClientUpdate) Reset()         { *m = ClientUpdate{} }
func (m *ClientUpdate) String() string { return proto.CompactTextString(m) }
func (*ClientUpdate) ProtoMessage()    {}
func (*ClientUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{20}
}

func (m *ClientUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientUpdate.Unmarshal(m, b)
}
func (m *ClientUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientUpdate.Marshal(b, m, deterministic)
}
func (m *ClientUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientUpdate.Merge(m, src)
}
func (m *ClientUpdate) XXX_Size() int {
	return xxx_messageInfo_ClientUpdate.Size(m)
}
func (m *ClientUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ClientUpdate proto.InternalMessageInfo

type isClientUpdate_Message interface {
	isClientUpdate_Message()
}

type ClientUpdate_Up struct {
	Up *Connect `protobuf:"bytes,1,opt,name=up,proto3,oneof"`
}

type ClientUpdate_Ping struct {
	Ping *Ping `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type ClientUpdate_Down struct {
	Down *Disconnect `protobuf:"bytes,3,opt,name=down,proto3,oneof"`
}

func (*ClientUpdate_Up) isClientUpdate_Message() {}

func (*ClientUpdate_Ping) isClientUpdate_Message() {}

func (*ClientUpdate_Down) isClientUpdate_Message() {}

func (m *ClientUpdate) GetMessage() isClientUpdate_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ClientUpdate) GetUp() *Connect {
	if x, ok := m.GetMessage().(*ClientUpdate_Up); ok {
		return x.Up
	}
	return nil
}

func (m *ClientUpdate) GetPing() *Ping {
	if x, ok := m.GetMessage().(*ClientUpdate_Ping); ok {
		return x.Ping
	}
	return nil
}

func (m *ClientUpdate) GetDown() *Disconnect {
	if x, ok := m.GetMessage().(*ClientUpdate_Down); ok {
		return x.Down
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ClientUpdate) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ClientUpdate_Up)(nil),
		(*ClientUpdate_Ping)(nil),
		(*ClientUpdate_Down)(nil),
	}
}

type ServerUpdate struct {
	// Types that are valid to be assigned to Message:
	//	*ServerUpdate_Data
	//	*ServerUpdate_Pong
	Message              isServerUpdate_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ServerUpdate) Reset()         { *m = ServerUpdate{} }
func (m *ServerUpdate) String() string { return proto.CompactTextString(m) }
func (*ServerUpdate) ProtoMessage()    {}
func (*ServerUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e50ccc58c7b575d, []int{21}
}

func (m *ServerUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerUpdate.Unmarshal(m, b)
}
func (m *ServerUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerUpdate.Marshal(b, m, deterministic)
}
func (m *ServerUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerUpdate.Merge(m, src)
}
func (m *ServerUpdate) XXX_Size() int {
	return xxx_messageInfo_ServerUpdate.Size(m)
}
func (m *ServerUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ServerUpdate proto.InternalMessageInfo

type isServerUpdate_Message interface {
	isServerUpdate_Message()
}

type ServerUpdate_Data struct {
	Data *MessageData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type ServerUpdate_Pong struct {
	Pong *Pong `protobuf:"bytes,2,opt,name=pong,proto3,oneof"`
}

func (*ServerUpdate_Data) isServerUpdate_Message() {}

func (*ServerUpdate_Pong) isServerUpdate_Message() {}

func (m *ServerUpdate) GetMessage() isServerUpdate_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ServerUpdate) GetData() *MessageData {
	if x, ok := m.GetMessage().(*ServerUpdate_Data); ok {
		return x.Data
	}
	return nil
}

func (m *ServerUpdate) GetPong() *Pong {
	if x, ok := m.GetMessage().(*ServerUpdate_Pong); ok {
		return x.Pong
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerUpdate) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerUpdate_Data)(nil),
		(*ServerUpdate_Pong)(nil),
	}
}

func init() {
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*SignUpRequest)(nil), "api.SignUpRequest")
	proto.RegisterType((*SuccessReply)(nil), "api.SuccessReply")
	proto.RegisterType((*SignInRequest)(nil), "api.SignInRequest")
	proto.RegisterType((*SignInReply)(nil), "api.SignInReply")
	proto.RegisterType((*RefreshRequest)(nil), "api.RefreshRequest")
	proto.RegisterType((*RefreshReply)(nil), "api.RefreshReply")
	proto.RegisterType((*NewChanRequest)(nil), "api.NewChanRequest")
	proto.RegisterType((*JoinChanRequest)(nil), "api.JoinChanRequest")
	proto.RegisterType((*Channel)(nil), "api.Channel")
	proto.RegisterType((*GetChansRequest)(nil), "api.GetChansRequest")
	proto.RegisterType((*SearchChansRequest)(nil), "api.SearchChansRequest")
	proto.RegisterType((*ChansReply)(nil), "api.ChansReply")
	proto.RegisterType((*LeaveChanRequest)(nil), "api.LeaveChanRequest")
	proto.RegisterType((*Connect)(nil), "api.Connect")
	proto.RegisterType((*Disconnect)(nil), "api.Disconnect")
	proto.RegisterType((*PublishRequest)(nil), "api.PublishRequest")
	proto.RegisterType((*MessageData)(nil), "api.MessageData")
	proto.RegisterType((*Ping)(nil), "api.Ping")
	proto.RegisterType((*Pong)(nil), "api.Pong")
	proto.RegisterType((*ClientUpdate)(nil), "api.ClientUpdate")
	proto.RegisterType((*ServerUpdate)(nil), "api.ServerUpdate")
}

func init() { proto.RegisterFile("pkg/api/api.proto", fileDescriptor_7e50ccc58c7b575d) }

var fileDescriptor_7e50ccc58c7b575d = []byte{
	// 692 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x5d, 0x4f, 0x1b, 0x39,
	0x14, 0xcd, 0xc7, 0x40, 0x92, 0x9b, 0x6c, 0x12, 0xbc, 0xac, 0x36, 0x8a, 0x76, 0x5b, 0xe4, 0x02,
	0x8a, 0xfa, 0x40, 0x69, 0x50, 0x3f, 0x78, 0xe9, 0x43, 0x83, 0x54, 0xa8, 0x4a, 0x85, 0x26, 0xf0,
	0x03, 0xcc, 0xe4, 0x36, 0x58, 0x24, 0xb6, 0x19, 0x7b, 0x88, 0x78, 0xec, 0xcf, 0xe9, 0xbf, 0xac,
	0xec, 0xf1, 0x0c, 0x93, 0x34, 0x15, 0x7d, 0x88, 0x34, 0xf7, 0xde, 0x73, 0xee, 0x1c, 0x9f, 0xf8,
	0x24, 0xb0, 0xa5, 0x6e, 0xa7, 0xaf, 0x98, 0xe2, 0xf6, 0x73, 0xa0, 0x62, 0x69, 0x24, 0xa9, 0x32,
	0xc5, 0xe9, 0x7b, 0x08, 0xae, 0x34, 0xc6, 0x64, 0x1b, 0x36, 0x70, 0xce, 0xf8, 0xac, 0x57, 0xde,
	0x29, 0x0f, 0x1a, 0x61, 0x5a, 0x90, 0x3e, 0xd4, 0x15, 0xd3, 0x7a, 0x21, 0xe3, 0x49, 0xaf, 0xe2,
	0x06, 0x79, 0x4d, 0x0f, 0xe0, 0xaf, 0x31, 0x9f, 0x8a, 0x2b, 0x15, 0xe2, 0x5d, 0x82, 0xda, 0x90,
	0xff, 0x21, 0x48, 0x34, 0xc6, 0x6e, 0x43, 0x73, 0xd8, 0x38, 0xb0, 0x6f, 0xb2, 0xbb, 0x43, 0xd7,
	0xa6, 0x6d, 0x68, 0x8d, 0x93, 0x28, 0x42, 0xad, 0x43, 0x54, 0xb3, 0x87, 0x8c, 0x7f, 0x26, 0xfe,
	0x90, 0xff, 0x02, 0x9a, 0x19, 0x5e, 0xcd, 0x1e, 0xac, 0x60, 0x23, 0x6f, 0x51, 0x64, 0x82, 0x5d,
	0x41, 0xbb, 0xd0, 0x0e, 0xf1, 0x5b, 0x8c, 0xfa, 0xc6, 0x6f, 0xa5, 0x43, 0x68, 0xe5, 0x1d, 0xcb,
	0xa3, 0xd0, 0x8a, 0xd3, 0xfa, 0xb2, 0x40, 0x5f, 0xea, 0xd1, 0x5d, 0x68, 0x7f, 0xc5, 0xc5, 0xe8,
	0x86, 0xe5, 0xda, 0x08, 0x04, 0x82, 0xcd, 0xd1, 0xa3, 0xdd, 0x33, 0xdd, 0x83, 0xce, 0x67, 0xc9,
	0xc5, 0x53, 0xb0, 0x11, 0xd4, 0x2c, 0x44, 0xe0, 0x8c, 0xb4, 0xa1, 0xc2, 0x27, 0x7e, 0x58, 0xe1,
	0x93, 0x1c, 0x5e, 0x79, 0x84, 0xdb, 0x73, 0xc9, 0x85, 0xc0, 0x49, 0xaf, 0xba, 0x53, 0x1e, 0xd4,
	0xc3, 0xb4, 0xa0, 0x5b, 0xd0, 0xf9, 0x84, 0xc6, 0xee, 0xd1, 0xd9, 0xc1, 0x5e, 0x02, 0x19, 0x23,
	0x8b, 0xa3, 0x9b, 0x62, 0xd7, 0xd2, 0xb9, 0x50, 0x89, 0xc9, 0x6c, 0x71, 0x05, 0x7d, 0x0b, 0xe0,
	0x51, 0xd6, 0x82, 0x01, 0xd4, 0xa3, 0x54, 0x91, 0xee, 0x95, 0x77, 0xaa, 0x83, 0xe6, 0xb0, 0xe5,
	0xcc, 0xf6, 0x32, 0xc3, 0x7c, 0x4a, 0xf7, 0xa1, 0xfb, 0x05, 0xd9, 0x3d, 0x3e, 0x75, 0xc6, 0x06,
	0xd4, 0x46, 0x52, 0x08, 0x8c, 0x0c, 0x6d, 0x01, 0x9c, 0x70, 0x1d, 0xf9, 0xea, 0x03, 0xb4, 0x2f,
	0x92, 0xeb, 0x19, 0xcf, 0xbf, 0x8f, 0x75, 0x74, 0xd2, 0x83, 0x5a, 0x24, 0x85, 0x41, 0x61, 0xbc,
	0x15, 0x59, 0x49, 0xcf, 0xa1, 0x79, 0x8e, 0x5a, 0xb3, 0x29, 0x9e, 0x30, 0xc3, 0xd6, 0x92, 0xbb,
	0x50, 0xd5, 0x78, 0xe7, 0x88, 0x1b, 0xa1, 0x7d, 0x2c, 0xae, 0xab, 0x2e, 0xaf, 0xdb, 0x85, 0xe0,
	0x82, 0x8b, 0x29, 0xf9, 0x0f, 0x1a, 0x86, 0xcf, 0x51, 0x1b, 0x36, 0x57, 0x6e, 0x59, 0x10, 0x3e,
	0x36, 0x1c, 0x4a, 0x3e, 0x89, 0xfa, 0x5e, 0x86, 0xd6, 0x68, 0xc6, 0x51, 0x98, 0x2b, 0x35, 0x61,
	0x06, 0xc9, 0x33, 0xa8, 0x24, 0xca, 0xdf, 0x5e, 0x6f, 0x68, 0xea, 0xc2, 0x69, 0x29, 0xac, 0x24,
	0x8a, 0x3c, 0x87, 0x40, 0x71, 0x31, 0x75, 0x4a, 0xb3, 0xfb, 0x6d, 0xd5, 0x9c, 0x96, 0x42, 0x37,
	0x20, 0x7b, 0x10, 0x4c, 0xe4, 0x42, 0x38, 0xd1, 0xcd, 0x61, 0xc7, 0x01, 0x1e, 0xbd, 0xb4, 0x30,
	0x3b, 0xfe, 0xd8, 0x80, 0xda, 0x3c, 0xf5, 0x84, 0x5e, 0x43, 0x6b, 0x8c, 0xf1, 0x3d, 0xc6, 0x5e,
	0xc2, 0x3e, 0x04, 0x13, 0x66, 0x98, 0x17, 0xd1, 0x75, 0x1b, 0x0a, 0xfe, 0xb9, 0x15, 0xd6, 0x47,
	0x2b, 0x45, 0xae, 0x4a, 0x91, 0x5e, 0x8a, 0x14, 0xd3, 0xc2, 0x3b, 0x86, 0x3f, 0x02, 0xa8, 0x5f,
	0xe2, 0xcc, 0xdd, 0x01, 0xf2, 0x1a, 0x36, 0xd3, 0xd0, 0x13, 0xe2, 0x48, 0x4b, 0xbf, 0x00, 0xfd,
	0xad, 0xb4, 0x57, 0x4c, 0x79, 0x89, 0x1c, 0xa6, 0x94, 0x33, 0x51, 0xa0, 0xe4, 0xa1, 0xef, 0x77,
	0x97, 0x7a, 0x29, 0xe3, 0x08, 0x6a, 0x3e, 0xb2, 0xe4, 0x6f, 0x37, 0x5e, 0x8e, 0xb4, 0x7f, 0x4d,
	0x31, 0xd5, 0x29, 0xc9, 0x67, 0xd6, 0x93, 0x96, 0x13, 0xbc, 0x5e, 0xdb, 0x1b, 0xa8, 0x67, 0x11,
	0x26, 0xdb, 0x0e, 0xb0, 0x92, 0xe8, 0xf5, 0xb4, 0x23, 0xa8, 0x67, 0x69, 0xf4, 0xb4, 0x95, 0x70,
	0xf6, 0x3b, 0x79, 0xa0, 0x72, 0xd2, 0x31, 0x34, 0x0b, 0x79, 0x25, 0xff, 0xa6, 0x8b, 0x7f, 0x49,
	0xf0, 0x3a, 0xea, 0x3b, 0x68, 0xe4, 0x31, 0x24, 0xff, 0xb8, 0xf9, 0x6a, 0x2c, 0x7f, 0x27, 0xb4,
	0xe6, 0xe3, 0xe7, 0x4d, 0x59, 0x0e, 0xe3, 0x7a, 0xd2, 0x31, 0x34, 0x47, 0x72, 0x3e, 0x4f, 0x04,
	0x8f, 0xec, 0x9d, 0x4a, 0x31, 0xc5, 0x9b, 0x9e, 0xd1, 0x0a, 0x37, 0x8f, 0x96, 0x06, 0xe5, 0xc3,
	0xf2, 0xf5, 0xa6, 0xfb, 0x67, 0x39, 0xfa, 0x19, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x04, 0xcc, 0xab,
	0x6e, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TeleChanClient is the client API for TeleChan service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TeleChanClient interface {
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SuccessReply, error)
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInReply, error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshReply, error)
	NewChan(ctx context.Context, in *NewChanRequest, opts ...grpc.CallOption) (*SuccessReply, error)
	JoinChan(ctx context.Context, in *JoinChanRequest, opts ...grpc.CallOption) (*SuccessReply, error)
	GetChans(ctx context.Context, in *GetChansRequest, opts ...grpc.CallOption) (*ChansReply, error)
	SearchChans(ctx context.Context, in *SearchChansRequest, opts ...grpc.CallOption) (*ChansReply, error)
	LeaveChan(ctx context.Context, in *LeaveChanRequest, opts ...grpc.CallOption) (*SuccessReply, error)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*SuccessReply, error)
	Communicate(ctx context.Context, opts ...grpc.CallOption) (TeleChan_CommunicateClient, error)
}

type teleChanClient struct {
	cc *grpc.ClientConn
}

func NewTeleChanClient(cc *grpc.ClientConn) TeleChanClient {
	return &teleChanClient{cc}
}

func (c *teleChanClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SuccessReply, error) {
	out := new(SuccessReply)
	err := c.cc.Invoke(ctx, "/api.TeleChan/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teleChanClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInReply, error) {
	out := new(SignInReply)
	err := c.cc.Invoke(ctx, "/api.TeleChan/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teleChanClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshReply, error) {
	out := new(RefreshReply)
	err := c.cc.Invoke(ctx, "/api.TeleChan/Refresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teleChanClient) NewChan(ctx context.Context, in *NewChanRequest, opts ...grpc.CallOption) (*SuccessReply, error) {
	out := new(SuccessReply)
	err := c.cc.Invoke(ctx, "/api.TeleChan/NewChan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teleChanClient) JoinChan(ctx context.Context, in *JoinChanRequest, opts ...grpc.CallOption) (*SuccessReply, error) {
	out := new(SuccessReply)
	err := c.cc.Invoke(ctx, "/api.TeleChan/JoinChan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teleChanClient) GetChans(ctx context.Context, in *GetChansRequest, opts ...grpc.CallOption) (*ChansReply, error) {
	out := new(ChansReply)
	err := c.cc.Invoke(ctx, "/api.TeleChan/GetChans", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teleChanClient) SearchChans(ctx context.Context, in *SearchChansRequest, opts ...grpc.CallOption) (*ChansReply, error) {
	out := new(ChansReply)
	err := c.cc.Invoke(ctx, "/api.TeleChan/SearchChans", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teleChanClient) LeaveChan(ctx context.Context, in *LeaveChanRequest, opts ...grpc.CallOption) (*SuccessReply, error) {
	out := new(SuccessReply)
	err := c.cc.Invoke(ctx, "/api.TeleChan/LeaveChan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teleChanClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*SuccessReply, error) {
	out := new(SuccessReply)
	err := c.cc.Invoke(ctx, "/api.TeleChan/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teleChanClient) Communicate(ctx context.Context, opts ...grpc.CallOption) (TeleChan_CommunicateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TeleChan_serviceDesc.Streams[0], "/api.TeleChan/Communicate", opts...)
	if err != nil {
		return nil, err
	}
	x := &teleChanCommunicateClient{stream}
	return x, nil
}

type TeleChan_CommunicateClient interface {
	Send(*ClientUpdate) error
	Recv() (*ServerUpdate, error)
	grpc.ClientStream
}

type teleChanCommunicateClient struct {
	grpc.ClientStream
}

func (x *teleChanCommunicateClient) Send(m *ClientUpdate) error {
	return x.ClientStream.SendMsg(m)
}

func (x *teleChanCommunicateClient) Recv() (*ServerUpdate, error) {
	m := new(ServerUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TeleChanServer is the server API for TeleChan service.
type TeleChanServer interface {
	SignUp(context.Context, *SignUpRequest) (*SuccessReply, error)
	SignIn(context.Context, *SignInRequest) (*SignInReply, error)
	Refresh(context.Context, *RefreshRequest) (*RefreshReply, error)
	NewChan(context.Context, *NewChanRequest) (*SuccessReply, error)
	JoinChan(context.Context, *JoinChanRequest) (*SuccessReply, error)
	GetChans(context.Context, *GetChansRequest) (*ChansReply, error)
	SearchChans(context.Context, *SearchChansRequest) (*ChansReply, error)
	LeaveChan(context.Context, *LeaveChanRequest) (*SuccessReply, error)
	Publish(context.Context, *PublishRequest) (*SuccessReply, error)
	Communicate(TeleChan_CommunicateServer) error
}

// UnimplementedTeleChanServer can be embedded to have forward compatible implementations.
type UnimplementedTeleChanServer struct {
}

func (*UnimplementedTeleChanServer) SignUp(ctx context.Context, req *SignUpRequest) (*SuccessReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (*UnimplementedTeleChanServer) SignIn(ctx context.Context, req *SignInRequest) (*SignInReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedTeleChanServer) Refresh(ctx context.Context, req *RefreshRequest) (*RefreshReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refresh not implemented")
}
func (*UnimplementedTeleChanServer) NewChan(ctx context.Context, req *NewChanRequest) (*SuccessReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewChan not implemented")
}
func (*UnimplementedTeleChanServer) JoinChan(ctx context.Context, req *JoinChanRequest) (*SuccessReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinChan not implemented")
}
func (*UnimplementedTeleChanServer) GetChans(ctx context.Context, req *GetChansRequest) (*ChansReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChans not implemented")
}
func (*UnimplementedTeleChanServer) SearchChans(ctx context.Context, req *SearchChansRequest) (*ChansReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchChans not implemented")
}
func (*UnimplementedTeleChanServer) LeaveChan(ctx context.Context, req *LeaveChanRequest) (*SuccessReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveChan not implemented")
}
func (*UnimplementedTeleChanServer) Publish(ctx context.Context, req *PublishRequest) (*SuccessReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (*UnimplementedTeleChanServer) Communicate(srv TeleChan_CommunicateServer) error {
	return status.Errorf(codes.Unimplemented, "method Communicate not implemented")
}

func RegisterTeleChanServer(s *grpc.Server, srv TeleChanServer) {
	s.RegisterService(&_TeleChan_serviceDesc, srv)
}

func _TeleChan_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleChanServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TeleChan/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleChanServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeleChan_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleChanServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TeleChan/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleChanServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeleChan_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleChanServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TeleChan/Refresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleChanServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeleChan_NewChan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewChanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleChanServer).NewChan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TeleChan/NewChan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleChanServer).NewChan(ctx, req.(*NewChanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeleChan_JoinChan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinChanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleChanServer).JoinChan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TeleChan/JoinChan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleChanServer).JoinChan(ctx, req.(*JoinChanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeleChan_GetChans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleChanServer).GetChans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TeleChan/GetChans",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleChanServer).GetChans(ctx, req.(*GetChansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeleChan_SearchChans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchChansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleChanServer).SearchChans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TeleChan/SearchChans",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleChanServer).SearchChans(ctx, req.(*SearchChansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeleChan_LeaveChan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveChanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleChanServer).LeaveChan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TeleChan/LeaveChan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleChanServer).LeaveChan(ctx, req.(*LeaveChanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeleChan_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleChanServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TeleChan/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleChanServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeleChan_Communicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TeleChanServer).Communicate(&teleChanCommunicateServer{stream})
}

type TeleChan_CommunicateServer interface {
	Send(*ServerUpdate) error
	Recv() (*ClientUpdate, error)
	grpc.ServerStream
}

type teleChanCommunicateServer struct {
	grpc.ServerStream
}

func (x *teleChanCommunicateServer) Send(m *ServerUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func (x *teleChanCommunicateServer) Recv() (*ClientUpdate, error) {
	m := new(ClientUpdate)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TeleChan_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.TeleChan",
	HandlerType: (*TeleChanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _TeleChan_SignUp_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _TeleChan_SignIn_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _TeleChan_Refresh_Handler,
		},
		{
			MethodName: "NewChan",
			Handler:    _TeleChan_NewChan_Handler,
		},
		{
			MethodName: "JoinChan",
			Handler:    _TeleChan_JoinChan_Handler,
		},
		{
			MethodName: "GetChans",
			Handler:    _TeleChan_GetChans_Handler,
		},
		{
			MethodName: "SearchChans",
			Handler:    _TeleChan_SearchChans_Handler,
		},
		{
			MethodName: "LeaveChan",
			Handler:    _TeleChan_LeaveChan_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _TeleChan_Publish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Communicate",
			Handler:       _TeleChan_Communicate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/api/api.proto",
}
