// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignUpRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SignUpReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpReply) Reset()         { *m = SignUpReply{} }
func (m *SignUpReply) String() string { return proto.CompactTextString(m) }
func (*SignUpReply) ProtoMessage()    {}
func (*SignUpReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *SignUpReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpReply.Unmarshal(m, b)
}
func (m *SignUpReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpReply.Marshal(b, m, deterministic)
}
func (m *SignUpReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpReply.Merge(m, src)
}
func (m *SignUpReply) XXX_Size() int {
	return xxx_messageInfo_SignUpReply.Size(m)
}
func (m *SignUpReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpReply.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpReply proto.InternalMessageInfo

type SignInRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SignInReply struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInReply) Reset()         { *m = SignInReply{} }
func (m *SignInReply) String() string { return proto.CompactTextString(m) }
func (*SignInReply) ProtoMessage()    {}
func (*SignInReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *SignInReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInReply.Unmarshal(m, b)
}
func (m *SignInReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInReply.Marshal(b, m, deterministic)
}
func (m *SignInReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInReply.Merge(m, src)
}
func (m *SignInReply) XXX_Size() int {
	return xxx_messageInfo_SignInReply.Size(m)
}
func (m *SignInReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInReply.DiscardUnknown(m)
}

var xxx_messageInfo_SignInReply proto.InternalMessageInfo

func (m *SignInReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshRequest) Reset()         { *m = RefreshRequest{} }
func (m *RefreshRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshRequest) ProtoMessage()    {}
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *RefreshRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshRequest.Unmarshal(m, b)
}
func (m *RefreshRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshRequest.Marshal(b, m, deterministic)
}
func (m *RefreshRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshRequest.Merge(m, src)
}
func (m *RefreshRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshRequest.Size(m)
}
func (m *RefreshRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshRequest proto.InternalMessageInfo

type RefreshReply struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshReply) Reset()         { *m = RefreshReply{} }
func (m *RefreshReply) String() string { return proto.CompactTextString(m) }
func (*RefreshReply) ProtoMessage()    {}
func (*RefreshReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *RefreshReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshReply.Unmarshal(m, b)
}
func (m *RefreshReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshReply.Marshal(b, m, deterministic)
}
func (m *RefreshReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshReply.Merge(m, src)
}
func (m *RefreshReply) XXX_Size() int {
	return xxx_messageInfo_RefreshReply.Size(m)
}
func (m *RefreshReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshReply.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshReply proto.InternalMessageInfo

func (m *RefreshReply) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*SignUpRequest)(nil), "api.SignUpRequest")
	proto.RegisterType((*SignUpReply)(nil), "api.SignUpReply")
	proto.RegisterType((*SignInRequest)(nil), "api.SignInRequest")
	proto.RegisterType((*SignInReply)(nil), "api.SignInReply")
	proto.RegisterType((*RefreshRequest)(nil), "api.RefreshRequest")
	proto.RegisterType((*RefreshReply)(nil), "api.RefreshReply")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x1b, 0x28, 0xa5, 0xb9, 0xb6, 0xa8, 0x1c, 0x0c, 0x55, 0x24, 0x24, 0x64, 0x16, 0xa6,
	0x08, 0xa5, 0x0b, 0x3b, 0x53, 0xd7, 0xd0, 0xfe, 0x00, 0x23, 0x0e, 0x1a, 0x11, 0x1c, 0x63, 0xa7,
	0x42, 0xfd, 0x3d, 0xfc, 0x51, 0xe4, 0x73, 0x1c, 0xc5, 0x5b, 0xc7, 0xf7, 0xee, 0xbe, 0xf3, 0x7b,
	0x32, 0xa4, 0x52, 0x57, 0xb9, 0x36, 0x4d, 0xdb, 0xe0, 0xb9, 0xd4, 0x95, 0x78, 0x86, 0xf1, 0xce,
	0x92, 0xc1, 0x5b, 0xb8, 0xa0, 0x6f, 0x59, 0xd5, 0xab, 0xe4, 0x3e, 0x79, 0x4c, 0x4b, 0x2f, 0x30,
	0x83, 0xa9, 0x96, 0xd6, 0xfe, 0x36, 0xe6, 0x7d, 0x75, 0xc6, 0x83, 0x5e, 0x8b, 0x1c, 0x16, 0xaf,
	0xd5, 0xa7, 0xda, 0xe9, 0x92, 0x7e, 0x0e, 0x64, 0x5b, 0xbc, 0x83, 0xf1, 0xc1, 0x92, 0xe1, 0x0b,
	0xb3, 0x22, 0xcd, 0xdd, 0x4b, 0xee, 0x76, 0xc9, 0xb6, 0x58, 0xc0, 0x2c, 0xec, 0xeb, 0xfa, 0x18,
	0xf0, 0x8d, 0x3a, 0x11, 0x7f, 0xf0, 0xb8, 0xdb, 0xd7, 0xf5, 0xd1, 0xe5, 0x6d, 0x9b, 0x2f, 0x52,
	0x21, 0x2f, 0x0b, 0xb1, 0x84, 0xab, 0x92, 0x3e, 0x0c, 0xd9, 0x7d, 0x77, 0x55, 0x14, 0x30, 0xef,
	0x1d, 0xc7, 0x09, 0x98, 0x1b, 0xaf, 0xb7, 0x03, 0x3c, 0xf2, 0x8a, 0xbf, 0x04, 0xa6, 0x5b, 0xaa,
	0xe9, 0x65, 0x2f, 0x15, 0x3e, 0xc1, 0xc4, 0xc7, 0x46, 0xe4, 0x48, 0x51, 0xe7, 0x6c, 0x19, 0x79,
	0xae, 0xd7, 0x28, 0x10, 0x1b, 0x35, 0x20, 0xfa, 0x9a, 0x03, 0xa2, 0xab, 0x22, 0x46, 0xb8, 0x86,
	0xcb, 0x2e, 0x24, 0xde, 0xf0, 0x38, 0x2e, 0x91, 0x5d, 0xc7, 0x26, 0x43, 0x6f, 0x13, 0xfe, 0xc5,
	0xf5, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xf7, 0x30, 0x49, 0xd2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TeleChanClient is the client API for TeleChan service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TeleChanClient interface {
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpReply, error)
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInReply, error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshReply, error)
}

type teleChanClient struct {
	cc *grpc.ClientConn
}

func NewTeleChanClient(cc *grpc.ClientConn) TeleChanClient {
	return &teleChanClient{cc}
}

func (c *teleChanClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpReply, error) {
	out := new(SignUpReply)
	err := c.cc.Invoke(ctx, "/api.TeleChan/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teleChanClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInReply, error) {
	out := new(SignInReply)
	err := c.cc.Invoke(ctx, "/api.TeleChan/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teleChanClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshReply, error) {
	out := new(RefreshReply)
	err := c.cc.Invoke(ctx, "/api.TeleChan/Refresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeleChanServer is the server API for TeleChan service.
type TeleChanServer interface {
	SignUp(context.Context, *SignUpRequest) (*SignUpReply, error)
	SignIn(context.Context, *SignInRequest) (*SignInReply, error)
	Refresh(context.Context, *RefreshRequest) (*RefreshReply, error)
}

// UnimplementedTeleChanServer can be embedded to have forward compatible implementations.
type UnimplementedTeleChanServer struct {
}

func (*UnimplementedTeleChanServer) SignUp(ctx context.Context, req *SignUpRequest) (*SignUpReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (*UnimplementedTeleChanServer) SignIn(ctx context.Context, req *SignInRequest) (*SignInReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedTeleChanServer) Refresh(ctx context.Context, req *RefreshRequest) (*RefreshReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refresh not implemented")
}

func RegisterTeleChanServer(s *grpc.Server, srv TeleChanServer) {
	s.RegisterService(&_TeleChan_serviceDesc, srv)
}

func _TeleChan_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleChanServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TeleChan/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleChanServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeleChan_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleChanServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TeleChan/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleChanServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeleChan_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleChanServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TeleChan/Refresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleChanServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TeleChan_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.TeleChan",
	HandlerType: (*TeleChanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _TeleChan_SignUp_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _TeleChan_SignIn_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _TeleChan_Refresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
